Sia schema intermediate
TimeleapLabs/sia-schema pull request #1
Opened 2024-12-03 15:33 UTC by andreyluiz

2024-12-03 16:14 UTC, pouya-eghbali requested changes
Where did the `.yarn/sdks` and `.yarn/typescript` directories go? I'm asking because my vscode doesn't recognize the yarn installed types without it and it wasn't added to .gitignore by yarn.

Also, see my comment on package.json.

2024-12-03 16:14 UTC, pouya-eghbali commented on package.json
> +  "bin": "dist/cli.js",
change to:

```
  "bin": {
    "sia": "dist/cli.js"
  },
```

2024-12-04 07:48 UTC, andreyluiz commented
@pouya-eghbali This repo was using Yarn on the Plug'n Play mode. While nice, it requires some extra configuration, like the typescript and sdks directories. I added a `.yarnrc.yml` file which disabled the Plug'n Play and uses regular `node_modules`. This renders these two directories useless. When you run `yarn install` on your machine, it will use `node_modules` as well because it's configured for it.

2024-12-04 07:48 UTC, andreyluiz commented on package.json
> +  "bin": "dist/cli.js",
Should the cli also be name just `sia`?

2024-12-04 08:28 UTC, pouya-eghbali approved these changes

2024-12-04 08:30 UTC, merged